# Generated by Django 4.1.5 on 2023-01-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title_tag",
            field=models.CharField(default="My Blog", max_length=225),
        ),
    ]
