# Generated by Django 4.1.5 on 2023-02-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0006_alter_post_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="snippet",
            field=models.CharField(
                default="Click on the Link above to read blog post...", max_length=225
            ),
        ),
    ]
