# Generated by Django 4.1.5 on 2023-03-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0010_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
