# Generated by Django 4.1.5 on 2023-03-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0013_remove_profile_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
