# Generated by Django 4.1.5 on 2023-03-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0017_comment_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
