# Generated by Django 4.1.5 on 2023-03-15 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0021_ccomment_delete_comment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CComment",
            new_name="Comment",
        ),
    ]
